from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE
from pptx.dml.color import RGBColor


# ==========================================
# COLORS
# ==========================================

COLORS = {
    "primary": "2563EB",
    "secondary": "0F172A",
    "text": "334155",
    "light": "F8FAFC",
    "border": "E2E8F0",
    "white": "FFFFFF",
    "muted": "64748B",
}


def rgb(hex_color: str):
    """Convert HEX color to RGBColor."""
    hex_color = hex_color.replace("#", "")
    return RGBColor(
        int(hex_color[0:2], 16),
        int(hex_color[2:4], 16),
        int(hex_color[4:6], 16),
    )


# ==========================================
# MAIN PPT GENERATOR
# ==========================================

def generate_ppt(data: dict) -> Presentation:

    ppt = Presentation()

    # 16:9 wide layout
    ppt.slide_width = Inches(13.333)
    ppt.slide_height = Inches(7.5)

    # --------------------------------------
    # Cover
    # --------------------------------------

    add_cover(ppt, data)

    # --------------------------------------
    # Content slides
    # --------------------------------------

    slides = data.get("slides", [])

    for index, slide_data in enumerate(slides):

        add_content_slide(
            ppt=ppt,
            title=slide_data.get("title", ""),
            points=slide_data.get("points", []),
            page=index + 1,
            total=len(slides),
        )

    # --------------------------------------
    # Thank You
    # --------------------------------------

    add_thank_you(ppt)

    return ppt


# ==========================================
# COVER SLIDE
# ==========================================

def add_cover(ppt: Presentation, data: dict):

    slide = ppt.slides.add_slide(
        ppt.slide_layouts[6]
    )

    # Background
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = rgb(COLORS["primary"])

    # Top bar
    shape = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        Inches(0),
        Inches(0),
        Inches(13.333),
        Inches(0.18),
    )

    shape.fill.solid()
    shape.fill.fore_color.rgb = rgb("60A5FA")

    shape.line.color.rgb = rgb("60A5FA")

    # Title
    title_box = slide.shapes.add_textbox(
        Inches(0.7),
        Inches(1.7),
        Inches(12),
        Inches(0.8),
    )

    title_frame = title_box.text_frame
    title_frame.clear()

    paragraph = title_frame.paragraphs[0]
    paragraph.text = data.get("title", "")
    paragraph.alignment = PP_ALIGN.CENTER

    run = paragraph.runs[0]
    run.font.name = "Aptos"
    run.font.size = Pt(28)
    run.font.bold = True
    run.font.color.rgb = rgb(COLORS["white"])

    # Subtitle
    subtitle_box = slide.shapes.add_textbox(
        Inches(1),
        Inches(2.8),
        Inches(11.5),
        Inches(0.4),
    )

    subtitle_frame = subtitle_box.text_frame
    subtitle_frame.clear()

    paragraph = subtitle_frame.paragraphs[0]
    paragraph.text = data.get("subtitle", "")
    paragraph.alignment = PP_ALIGN.CENTER

    run = paragraph.runs[0]
    run.font.name = "Aptos"
    run.font.size = Pt(15)
    run.font.color.rgb = rgb("DBEAFE")

    # Footer
    footer_box = slide.shapes.add_textbox(
        Inches(0),
        Inches(6.9),
        Inches(13.333),
        Inches(0.2),
    )

    footer_frame = footer_box.text_frame
    footer_frame.clear()

    paragraph = footer_frame.paragraphs[0]
    paragraph.text = "Generated By CortexAI"
    paragraph.alignment = PP_ALIGN.CENTER

    run = paragraph.runs[0]
    run.font.name = "Aptos"
    run.font.size = Pt(10)
    run.font.color.rgb = rgb("BFDBFE")


# ==========================================
# CONTENT SLIDE
# ==========================================

def add_content_slide(
    ppt: Presentation,
    title: str,
    points: list,
    page: int,
    total: int,
):

    slide = ppt.slides.add_slide(
        ppt.slide_layouts[6]
    )

    # Background
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = rgb(COLORS["white"])

    # --------------------------------------
    # Title
    # --------------------------------------

    title_box = slide.shapes.add_textbox(
        Inches(0.6),
        Inches(0.35),
        Inches(10),
        Inches(0.4),
    )

    title_frame = title_box.text_frame
    title_frame.clear()

    paragraph = title_frame.paragraphs[0]
    paragraph.text = title

    run = paragraph.runs[0]
    run.font.name = "Aptos"
    run.font.size = Pt(24)
    run.font.bold = True
    run.font.color.rgb = rgb(COLORS["primary"])

    # --------------------------------------
    # Horizontal line
    # --------------------------------------

    line = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        Inches(0.6),
        Inches(0.85),
        Inches(12),
        Inches(0.015),
    )

    line.fill.solid()
    line.fill.fore_color.rgb = rgb(COLORS["border"])

    line.line.fill.background()

    # --------------------------------------
    # Points
    # --------------------------------------

    visible_points = points[:6]

    for i, point in enumerate(visible_points):

        y = 1.2 + (i * 0.75)

        # Background box
        box = slide.shapes.add_shape(
            MSO_SHAPE.ROUNDED_RECTANGLE,
            Inches(0.7),
            Inches(y),
            Inches(12),
            Inches(0.58),
        )

        box.fill.solid()

        if i % 2:
            box.fill.fore_color.rgb = rgb("F8FAFC")
        else:
            box.fill.fore_color.rgb = rgb("EFF6FF")

        box.line.color.rgb = rgb(COLORS["border"])

        # Bullet circle
        circle = slide.shapes.add_shape(
            MSO_SHAPE.OVAL,
            Inches(0.92),
            Inches(y + 0.18),
            Inches(0.12),
            Inches(0.12),
        )

        circle.fill.solid()
        circle.fill.fore_color.rgb = rgb(COLORS["primary"])

        circle.line.color.rgb = rgb(COLORS["primary"])

        # Point text
        text_box = slide.shapes.add_textbox(
            Inches(1.2),
            Inches(y + 0.08),
            Inches(11),
            Inches(0.35),
        )

        text_frame = text_box.text_frame
        text_frame.clear()
        text_frame.word_wrap = True

        paragraph = text_frame.paragraphs[0]
        paragraph.text = str(point)

        run = paragraph.runs[0]
        run.font.name = "Aptos"
        run.font.size = Pt(15)
        run.font.color.rgb = rgb(COLORS["text"])

    # --------------------------------------
    # Page number
    # --------------------------------------

    page_box = slide.shapes.add_textbox(
        Inches(12.1),
        Inches(6.9),
        Inches(0.8),
        Inches(0.2),
    )

    page_frame = page_box.text_frame
    page_frame.clear()

    paragraph = page_frame.paragraphs[0]
    paragraph.text = f"{page}/{total}"
    paragraph.alignment = PP_ALIGN.RIGHT

    run = paragraph.runs[0]
    run.font.name = "Aptos"
    run.font.size = Pt(10)
    run.font.color.rgb = rgb(COLORS["muted"])

    # --------------------------------------
    # CortexAI footer
    # --------------------------------------

    footer_box = slide.shapes.add_textbox(
        Inches(0.6),
        Inches(6.9),
        Inches(2),
        Inches(0.2),
    )

    footer_frame = footer_box.text_frame
    footer_frame.clear()

    paragraph = footer_frame.paragraphs[0]
    paragraph.text = "CortexAI"

    run = paragraph.runs[0]
    run.font.name = "Aptos"
    run.font.size = Pt(10)
    run.font.color.rgb = rgb(COLORS["muted"])


# ==========================================
# THANK YOU SLIDE
# ==========================================

def add_thank_you(ppt: Presentation):

    slide = ppt.slides.add_slide(
        ppt.slide_layouts[6]
    )

    # Background
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = rgb(COLORS["secondary"])

    # Thank You
    title_box = slide.shapes.add_textbox(
        Inches(0),
        Inches(2.2),
        Inches(13.333),
        Inches(0.8),
    )

    title_frame = title_box.text_frame
    title_frame.clear()

    paragraph = title_frame.paragraphs[0]
    paragraph.text = "Thank You"
    paragraph.alignment = PP_ALIGN.CENTER

    run = paragraph.runs[0]
    run.font.name = "Aptos"
    run.font.size = Pt(34)
    run.font.bold = True
    run.font.color.rgb = rgb(COLORS["white"])

    # Footer
    footer_box = slide.shapes.add_textbox(
        Inches(0),
        Inches(6.9),
        Inches(13.333),
        Inches(0.2),
    )

    footer_frame = footer_box.text_frame
    footer_frame.clear()

    paragraph = footer_frame.paragraphs[0]
    paragraph.text = "Generated By CortexAI"
    paragraph.alignment = PP_ALIGN.CENTER

    run = paragraph.runs[0]
    run.font.name = "Aptos"
    run.font.size = Pt(10)
    run.font.color.rgb = rgb("94A3B8")