from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    ListFlowable,
    ListItem,
)


def generate_pdf(data: dict) -> bytes:

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50,
        title=data.get("title", ""),
        author="CortexAI",
        creator="CortexAI",
    )

    title_style = ParagraphStyle(
        "Title",
        fontName="Helvetica-Bold",
        fontSize=28,
        leading=34,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#111827"),
        spaceAfter=10,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        fontName="Helvetica",
        fontSize=12,
        leading=16,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#6B7280"),
    )

    heading_style = ParagraphStyle(
        "Heading",
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=colors.HexColor("#111827"),
        spaceAfter=8,
    )

    point_style = ParagraphStyle(
        "Point",
        fontName="Helvetica",
        fontSize=12,
        leading=18,
        textColor=colors.HexColor("#374151"),
    )

    footer_style = ParagraphStyle(
        "Footer",
        fontName="Helvetica",
        fontSize=10,
        leading=12,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#9CA3AF"),
    )

    story = []

    title = data.get("title", "")

    story.append(
        Paragraph(title, title_style)
    )

    subtitle = data.get("subtitle")

    if subtitle:
        story.append(
            Paragraph(subtitle, subtitle_style)
        )

    story.append(Spacer(1, 30))

    for section in data.get("sections", []):

        heading = section.get("heading", "")

        story.append(
            Paragraph(heading, heading_style)
        )

        points = section.get("points", [])

        if points:

            bullet_items = []

            for point in points:
                bullet_items.append(
                    ListItem(
                        Paragraph(
                            str(point),
                            point_style
                        ),
                        leftIndent=10,
                    )
                )

            story.append(
                ListFlowable(
                    bullet_items,
                    bulletType="bullet",
                    start="circle",
                    leftIndent=15,
                )
            )

        story.append(Spacer(1, 15))

    story.append(Spacer(1, 15))

    story.append(
        Paragraph(
            "Generated By CortexAI",
            footer_style
        )
    )

    doc.build(story)

    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes